---
title: "R Notebook"
output: html_notebook
Name: Diego Antonio Davila Fuentes 


---

Proyecto final


1. CONOCIMIENTO DE DATOS 



```{r}
library(tidyverse) 
library (ggplot2)
library (dbplyr)

yearly <- read.csv("deaths_handwashing.csv")

yearly
```

2. El alarmante numero de muertes 

```{r}
yearly <- mutate(yearly, proportion_deaths = deaths/births)
yearly

```

3. Muerte en las clinicas


```{r}

ggplot(yearly, aes(x=year, y=proportion_deaths, color = clinic))+ geom_line()


```


4 COMIENZA EL LAVADO DE MANOS


```{r}
monthly <- read.csv("deaths_clinic_1.csv")

monthly <- mutate(monthly, proportion_deaths = deaths/births)

head(monthly)
```

5 El efecto de lavado de manos 


```{r}

ggplot(monthly, aes( x=date, y=proportion_deaths, group = 1))+ geom_line() + labs(title="Proportion deaths") + geom_point(size=2, shape=21, fill= "green", colour= "red")+theme_minimal()
```

Los resultados del lavado de manos

```{r}
 
monthly <- mutate(monthly, handwashing_started = (date > 1847))
monthly

```
```{r}
ggplot(monthly, aes( x=date, y=proportion_deaths, group = 1, color = handwashing_started))+ geom_line()+labs(title = "Hands cleaning results", subtitle = "hand cleaning effect", x= "Date", y="Proportion deaths")


```

Mas lavado de manosm menos muertes

cuanto redujo la proporcion mensual de muertes en promedio
```{r}
month_summary <- monthly %>%
group_by(handwashing_started)%>%
  summarize(month_summary = mean(proportion_deaths))

month_summary
```

```{r}
Proporcion_mensual <- (0.10691840-0.03172764)
Proporcion_mensual
```


La proporcion mensualde muertes en promedio se redujo en 0.075


